### ISSUE TITLE
Grafana Question: Graphing a trace does not seem to work

### ISSUE THREAD

**Issue by JakeGreene** [kamon-io/docker-grafana-graphite#20]
I've been experimenting with Kamon and this docker image - which I'm really enjoying - for the last week, but I can't seem to get my traces to graph "correctly." 

I have a simple Akka application with two actors: A and B, where A sends a message to B, B responds after a random wait period, and then A finishes the TraceContext.

In Grafana I have a graph with the query `stats | timers | kamon | my_machine | trace | ping-pong | elapsed-time | mean_50`. I expect the graph to show the average time for a trace to complete - much like the graphs in your Readme - but I end up with an ever-increasing line which seems to show the total time the application has run for (e.g. the app has run for 10 minutes and so the trace time is 10 minutes)

Have I set-up my trace incorrectly? Is my query wrong? Is this a bug or are my expectations incorrect?

```
case object Ping
case object Pong

class Pinger(ponger: ActorRef) extends Actor {

  import context.system

  override def preStart(): Unit = {
    super.preStart()
    for (i <- 1 to 5000) {
      TraceRecorder.withNewTraceContext("ping-pong") {
        ponger ! Ping
      }
    }
  }

  def receive: Receive = {
    case Pong => TraceRecorder.finish()
  }
}

class Ponger extends Actor {
  def receive: Receive = {
    case Ping =>
      Thread.sleep((150 + (Math.random() * 200)).toLong)
      sender() ! Pong
  }
}
```
![ping-pong-trace](https://cloud.githubusercontent.com/assets/789639/6190340/26352c60-b36f-11e4-925c-d486f5a23af9.png)

I've been stuck on this for a couple days now. Any and all help is appreciated.

EDIT: As always, right after I ask a question a possible solution pops into my head. I added logging to see what the current context is when I receive a Ping and a Pong. It seems I always see the DefaultTraceContext.

```
case Pong =>
  log.info(s"Received Pong for context ${TraceRecorder.currentContext}")
```

```
case Ping =>
  log.info(s"Received Ping with ${TraceRecorder.currentContext}")
```

```
[info] [INFO] [02/13/2015 11:12:40.176] [kamon-test-akka.actor.default-dispatcher-10] [akka://kamon-test/user/ponger] Received Ping with kamon.trace.DefaultTraceContext@d781369
[info] [INFO] [02/13/2015 11:12:40.176] [kamon-test-akka.actor.default-dispatcher-6] [akka://kamon-test/user/pinger] Received Pong for context kamon.trace.DefaultTraceContext@d781369
```

It appears this problem is not related to grafana and instead is a problem with my tracing. I'm not sure what I have done that is different from Kamon's documentation but I'll dig a little deeper.

**Comment by ivantopo** [comment]
Hello Jake,

There is no Kamon or Grafana problem in you example as far as I see it, but maybe a misunderstanding on how your actors should behave. When you send the 5000 thousand messages to Ponger on Pinger's preStart, all of those TraceContexts start pretty much at the same time. At this point, you have 5000 messages waiting on Ponger's mailbox to be processed, then your Ponger actor will take the first of those messages, wait (let's say, around 300ms) and respond to Pinger which will finish the context and measure the elapsed time. Since actors process only one message at a time and you still have 4999 messages in the mailbox, by the time the Ponger actor takes the second message it has already been there for ~300ms + ~300ms for it's own sleep, gives you ~600ms elapsed time for the second trace, and that will continue to grow with each message. That's why you see that line only going up, because the elapsed times of traces are actually going up.

Let us know if you need any more help, regards!

**Comment by JakeGreene** [comment]
Well, don't I look like a fool. Thanks for the help, I'll spend some time with a rubber ducky next time I have an issue.

**Comment by ivantopo** [comment]
Don't worry Jake, feel free to ask if you need any help in the future and thanks for using Kamon!
